
CREATE TABLE `producto` (
  `ID_PRODUCTO` int NOT NULL,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `DESCRIPCION` varchar(45) DEFAULT NULL,
  `ID_PLATAFORMA` int DEFAULT NULL,
  `ID_TIPO_PRODUCTO` int DEFAULT NULL,
  `PRECIO` float DEFAULT NULL,
  `RUTA_IMAGEN` varchar(45) DEFAULT NULL,
  `STOCK` int DEFAULT NULL,
  `ID_CATEGORIA` int DEFAULT NULL,
  `VALORACION` float DEFAULT NULL,
  `RUTA_SNAPSHOTS` mediumtext,
  PRIMARY KEY (`ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;